/**
 * AIProposalModal — show an AI-generated policy draft with a diff
 * against the current version, the LLM's structured replacements list,
 * and Accept / Reject controls.
 *
 * Phase 1 of the AI accelerators plan. The modal never auto-applies the
 * draft: the user must explicitly click "Save as new version" to create
 * a `PolicyVersion` row, which is when the audit trail is written.
 */

"use client";

import { useState } from "react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PolicyDiff } from "./policy-diff";
import type { PolicyDraftFromContext } from "@/lib/api-client";

interface AIProposalModalProps {
  open: boolean;
  draft: PolicyDraftFromContext | null;
  baseHtml: string;
  /** Called when the user accepts; should create a new policy version. */
  onAccept: (acceptedHtml: string, changeNotes: string) => Promise<void> | void;
  onClose: () => void;
}

const SOURCE_LABELS: Record<PolicyDraftFromContext["sourceLabel"], string> = {
  template: "Source: matched policy template",
  current_version: "Source: rewriting current draft (no template found)",
  empty: "Source: empty policy",
};

export function AIProposalModal({
  open,
  draft,
  baseHtml,
  onAccept,
  onClose,
}: AIProposalModalProps) {
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showReplacements, setShowReplacements] = useState(true);

  if (!draft) {
    return (
      <Modal open={open} onClose={onClose} title="AI policy draft">
        <p className="py-12 text-center text-sm text-neutral-500">No draft generated yet.</p>
      </Modal>
    );
  }

  const replacementCount = draft.replacements.length;
  const unfilledCount = draft.unfilled.length;

  async function handleAccept() {
    if (!draft) return;
    setSaving(true);
    setError(null);
    try {
      const notes =
        `AI-drafted from organisation context · ${draft.provider}/${draft.model}` +
        (unfilledCount > 0 ? ` · ${unfilledCount} placeholders left for manual fill` : "");
      await onAccept(draft.draftHtml, notes);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save the AI draft");
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal open={open} onClose={onClose} title="AI policy draft" size="2xl">
      <div className="space-y-4">
        {/* Provenance / metadata strip */}
        <div className="flex flex-wrap items-center gap-2 rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2 text-xs dark:border-neutral-700 dark:bg-neutral-800/50">
          <Badge variant="info">{SOURCE_LABELS[draft.sourceLabel]}</Badge>
          <span className="text-neutral-600 dark:text-neutral-300">
            Generated by <strong>{draft.provider}</strong> / <code>{draft.model}</code>
          </span>
          {draft.templateSlug && (
            <span className="text-neutral-500">
              · template: <code>{draft.templateSlug}</code>
            </span>
          )}
        </div>

        {/* Replacement / unfilled summary */}
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-3">
          <SummaryStat label="Placeholders filled" value={replacementCount} tone="success" />
          <SummaryStat
            label="Left for review"
            value={unfilledCount}
            tone={unfilledCount > 0 ? "warning" : "neutral"}
          />
          <SummaryStat
            label="Draft size"
            value={`${Math.round(draft.draftHtml.length / 1024)} KB`}
            tone="neutral"
          />
        </div>

        {/* Replacement detail (collapsed by default once >5) */}
        {replacementCount > 0 && (
          <div className="rounded-lg border border-neutral-200 dark:border-neutral-700">
            <button
              type="button"
              className="flex w-full items-center justify-between px-3 py-2 text-left text-xs font-semibold uppercase tracking-wide text-neutral-700 hover:bg-neutral-50 dark:text-neutral-200 dark:hover:bg-neutral-800"
              onClick={() => setShowReplacements((v) => !v)}
            >
              <span>
                {showReplacements ? "Hide" : "Show"} {replacementCount} replacements
              </span>
              <span aria-hidden>{showReplacements ? "−" : "+"}</span>
            </button>
            {showReplacements && (
              <div className="max-h-40 overflow-auto border-t border-neutral-200 px-3 py-2 text-xs dark:border-neutral-700">
                <ul className="space-y-1">
                  {draft.replacements.map((r, idx) => (
                    <li key={`${r.placeholder}-${idx}`} className="flex items-start gap-2">
                      <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-[11px] dark:bg-neutral-800">
                        [[{r.placeholder}]]
                      </code>
                      <span className="text-neutral-500">→ from {r.source}:</span>
                      <span className="flex-1 text-neutral-700 dark:text-neutral-300 line-clamp-2">
                        {r.value}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {unfilledCount > 0 && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-200">
            <strong>{unfilledCount}</strong> placeholder{unfilledCount === 1 ? "" : "s"} could not
            be confidently filled from your organisation context. They are kept visible in the draft
            — answer the related questions in <em>Settings → AI Context</em> and re-generate to fill
            them.
          </div>
        )}

        {/* The diff itself */}
        <div className="max-h-[55vh] overflow-auto rounded-lg border border-neutral-200 p-3 dark:border-neutral-700">
          <PolicyDiff
            beforeHtml={baseHtml}
            afterHtml={draft.draftHtml}
            beforeLabel="Current version"
            afterLabel="AI proposal"
          />
        </div>

        {error && (
          <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-800 dark:bg-red-950 dark:text-red-300">
            {error}
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center justify-end gap-2 border-t border-neutral-200 pt-3 dark:border-neutral-700">
          <Button variant="ghost" onClick={onClose} disabled={saving}>
            Discard
          </Button>
          <Button onClick={handleAccept} disabled={saving}>
            {saving ? "Saving…" : "Save as new version"}
          </Button>
        </div>
      </div>
    </Modal>
  );
}

interface SummaryStatProps {
  label: string;
  value: number | string;
  tone: "success" | "warning" | "neutral";
}

function SummaryStat({ label, value, tone }: SummaryStatProps) {
  const toneClass =
    tone === "success"
      ? "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-800 dark:bg-emerald-950 dark:text-emerald-200"
      : tone === "warning"
        ? "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-200"
        : "border-neutral-200 bg-neutral-50 text-neutral-700 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-300";
  return (
    <div className={`rounded-lg border ${toneClass} px-3 py-2`}>
      <div className="text-[11px] uppercase tracking-wide opacity-75">{label}</div>
      <div className="mt-1 text-lg font-semibold">{value}</div>
    </div>
  );
}
